#rangle settings
obstacle_range: 3 #lidar range
raytrace_range: 3 #clear the overlapped obstacles on the path, only for the obstacle layer

#hexagonal footprint
footprint: [[0,0.15],[0.1299,0.075],[0.1299,-0.075],[0,-0.15],[-0.1299,-0.075],[-0.1299,0.075]]

#tf
global_frame: map
robot_base_frame: base_footprint

#map info
map_topic: map
subscribe_to_updates: true
update_frequency: 10.0  #frequency to update costmap
publish_frequency: 10.0 #frequency to publish the new costmap to Rviz