global_costmap:
  static_map: true
  rolling_window: false

  transform_tolerance: 0.2
  resolution: 0.1
  visualize_potential: true

  plugins:
  # ... first layer  
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    # - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"} 
  # ... my own plugins   
    # - {name: simple_layer, type: "simple_layer_namespace::GridLayer"}   
    # - {name: simple_layer, type: "simple_layer_namespace::SimpleLayer"}  
    - {name: lidar_obstacle_layer, type: "lidar_obstacle_layer_namespace::LidarObstacleLayer"} 
  # ... final layer
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
    

  static_layer:
    enabled: true
    map_topic: map
    subscribe_to_updates: false

  # obstacle_layer:
  #   enabled: true
  #   observation_sources: laser_scan_sensor
  #   laser_scan_sensor: {sensor_frame: laser_frame, data_type: LaserScan, topic: scan, marking: true, clearing: true}

  lidar_obstacle_layer:
    enabled: true
    obstacle_topic: obstacles_to_map #test
    obstacle_radius: 0.15
    expand_division: 30 #total points of the expanded profile

  # simple_layer:
  #   enabled: true
  #   observation_sources: 
  #     camera: true
  #     tracker: false
  #     lidar: false
  #   update_frequency: 1.0
  #   tolerance: 
  #     sample: 0.07
  #     rival: 0.15

  inflation_layer:
    enabled: true
    cost_scaling_factor: 3.0
    inflation_radius: 0.2