local_costmap:
  update_frequency: 1.0
  publish_frequency: 1.0
  transform_tolerance: 0.2
  static_map: false
  rolling_window: true
  width: 1.0
  height: 1.0
  resolution: 0.01

  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}