update_frequency: 3
obstacles:
  - {from: camera, motion_type: static, position: "[[1, 0.5], [1.5, 0.7], [2.5,1.5]]", stdev: 0.01}
  - {from: tracker, motion_type: reciprocation, position: "[[1, 0.5], [2.5, 2]]", stdev: 0.01}

