# |-------------------------------------|
# |    |   |    | ------- |    |   |    |
# |____|3 2|__7_|         |____|   |__6_|
# |          1                          |
# |  4                                  |
# |------                          -----|
# |                                     |
# |____     ____           ____     ____|
# |  5 |   |    |         |    |   |    |
# |    |   |    | ------- |    |   |    |    
# |-------------------------------------|

- xyz: [1.875, 1.775, 1.0]
- xyz: [1.875, 1.275, 1.0]
- xyz: [2.225, 1.775, 1.0]
- xyz: [2.425, 1.775, 1.0]
- xyz: [2.775, 1.275, 1.0]
- xyz: [1.500, 0.225, 1.0]
- xyz: [0.225, 1.775, 1.0]
- xyz: [1.125, 0.225, 1.0]
