# |-------------------------------------|
# |  7 |   |    | ------- |    |   |    |
# |____|   |____|         |__1_|3 4|____|
# |                          2          |
# |                                  5  |
# |------                          -----|
# |                                     |
# |____     ____           ____     ____|
# |    |   |    |    6    |    |   |    |
# |    |   |  8 | ------- |    |   |    |    
# |-------------------------------------|

- xyz: [path, 1.875, 1.775, 1.0]
- xyz: [path, 1.875, 1.275, 1.0]
- xyz: [path, 2.225, 1.775, 1.0]
- xyz: [path, 2.425, 1.775, 1.0]
- xyz: [path, 2.775, 1.275, 1.0]
- xyz: [path, 1.500, 0.225, 1.0]
- xyz: [path, 0.225, 1.775, 1.0]
- xyz: [path, 1.125, 0.225, 1.0]
