# for piko
- xyz: [path, 2.7, 0.55, 1]
- xyz: [path, 1.85, 0.4, 2]
- xyz: [path, 1.85, 0.7, 2]
- xyz: [path, 2.45, 0.25, 1]
- xyz: [path, 0.2, 0.75, 1]
- xyz: [path, 2.8, 1.75, 1]

# for peko
# - xyz: [path, 1.875, 0.225, 1]
# - xyz: [path, 1.875, 0.225, 1]
# - xyz: [path, 1.875, 0.725, 0.75]
# - xyz: [path, 2.225, 0.225, 1]
# - xyz: [path, 2.425, 0.225, 1]
# - xyz: [path, 0.2, 0.75, 1]