# for piko
# - xyz: [path, 1.1, 0.25, 1]
# - xyz: [path, 1.1, 0.25, 1]
# - xyz: [path, 1.1, 0.75, 0.75]
# - xyz: [path, 0.75, 0.25, 1]
# - xyz: [path, 0.55, 0.25, 1]
# - xyz: [path, 2.75, 0.75, 1]

# for peko
- xyz: [path, 1.15, 1.75, 1]
- xyz: [path, 1.15, 1.75, 1]
- xyz: [path, 0.6, 1.75, 2]
- xyz: [path, 1.15, 1.25, 1]
- xyz: [path, 0.25, 0.25, 1]
- xyz: [path, 2.8, 1.3, 1]