# |-------------------------------------|
# |    |   | 8  | ------- |    |   |    |
# |____|   |____|    6    |____|   |____|
# |                                     |
# |                                     |
# |------                          -----|
# |                                  5  |
# |____     ____           __2_     ____|
# |    |   |    |         |    |3 4|    |
# | 7  |   |    | ------- |  1 |   |    |    
# |-------------------------------------|

- xyz: [path, 1.125, 1.775, 1.0]
- xyz: [dock, 1.0, 1.275, 1.0]
# - path: [1.125, 1.275, 1.0]
# - path: [0.775, 1.775, 1.0]
# - path: [0.575, 1.775, 1.0]
# - path: [0.225, 1.275, 1.0]
# - path: [0.225, 0.225, 1.0]
# - path: [2.775, 1.775, 1.0]
# - path: [1.025, 1.775, 1.0]