#------------------MAP--------------------

# |-------------------------------------|
# | 2  |   | 6  | ------- | 14 |   | 20 |
# |____|   |____|   12    |____|   |____|
# |                                |    |
# | 4        8      10      16     | 18 |
# |------                          -----|
# | 3        5      11      15     | 19 |
# |____     ____           ____    |____|
# |    |   |    |    9    |    |   |    |
# | 1  |   | 7  | ------- | 13 |   | 17 |    
# |-------------------------------------|

#----------------POINTS-------------------
#1
- xyz: [path, 0.225, 0.225, 1.0]
#2
- xyz: [path, 0.225, 1.775, 1.0]
#3
- xyz: [path, 0.225, 0.725, 1.0]
#4
- xyz: [path, 0.225, 1.275, 1.0]
#-----------------------------------------
#5
- xyz: [path, 1.125, 0.725, 1.0]
#6
- xyz: [path, 1.125, 1.775, 1.0]
#7
- xyz: [path, 1.125, 0.225, 1.0]
#8
- xyz: [path, 1.125, 1.275, 1.0]
#-----------------------------------------
#9
- xyz: [path, 1.500, 0.225, 1.0]
#10
- xyz: [path, 1.500, 1.275, 1.0]
#11
- xyz: [path, 1.500, 0.725, 1.0]
#12
- xyz: [path, 1.500, 1.775, 1.0]
#-----------------------------------------
#13
- xyz: [path, 1.875, 0.225, 1.0]
#14
- xyz: [path, 1.875, 1.775, 1.0]
#15
- xyz: [path, 1.875, 0.725, 1.0]
#16
- xyz: [path, 1.875, 1.275, 1.0]
#-----------------------------------------
#17
- xyz: [path, 2.775, 0.225, 1.0]
#18
- xyz: [path, 2.775, 1.275, 1.0]
#19
- xyz: [path, 2.775, 0.725, 1.0]
#20
- xyz: [path, 2.775, 1.775, 1.0]