# |-------------------------------------|
# |    |   |    | ------- |    |   |    |
# |__6_|   |____|         |____|   |____|
# |                                     |
# |                                     |
# |------                          -----|
# |  5                                  |
# |____     __2_           ____     ____|
# |    |4 3|  18|         |    |   |  7 |
# |    |   |    | ------- |    |   |    |    
# |-------------------------------------|

- xyz: [path, 1.125, 0.225, 1.0]
- xyz: [path, 1.125, 0.725, 1.0]
- xyz: [path, 0.775, 0.225, 1.0]
- xyz: [path, 0.575, 0.225, 1.0]
- xyz: [path, 0.225, 0.725, 1.0]
- xyz: [path, 0.225, 1.775, 1.0]
- xyz: [path, 2.775, 0.225, 1.0]
- xyz: [path, 1.125, 0.225, 1.0]