# |-------------------------------------|
# |    |   |    | ------- |    |   |    |
# |____|3 2|__7_|         |____|   |__6_|
# |          1                          |
# |  4                                  |
# |------                          -----|
# |                                     |
# |____     ____           ____     ____|
# |  5 |   |    |         |    |   |    |
# |    |   |    | ------- |    |   |    |
# |-------------------------------------|

- xyz: [1.125, 1.775, 1.0]
- xyz: [1.125, 1.275, 1.0]
- xyz: [0.775, 1.775, 1.0]
- xyz: [0.575, 1.775, 1.0]
- xyz: [0.225, 1.275, 1.0]
- xyz: [0.225, 0.225, 1.0]
- xyz: [2.775, 1.775, 1.0]
- xyz: [1.025, 1.775, 1.0]