# |-------------------------------------|
# |    |   | 8  | ------- |    |   |    |
# |____|   |____|    6    |____|   |____|
# |                                     |
# |                                     |
# |------                          -----|
# |                                  5  |
# |____     ____           __2_     ____|
# |    |   |    |         |    |3 4|    |
# | 7  |   |    | ------- |  1 |   |    |    
# |-------------------------------------|

- xyz: [path, 1.875, 0.225, 1.0]
- xyz: [dock, 1.975, 0.325, 1.0]
- xyz: [dock, 1, 0.325, 1.0]
# - path: [1.875, 0.725, 1.0]
# - path: [2.225, 0.225, 1.0]
# - path: [2.425, 0.225, 1.0]
# - path: [2.775, 0.725, 1.0]
# - path: [1.500, 1.775, 1.0]
# - path: [0.225, 0.225, 1.0]
# - path: [1.325, 1.775, 1.0]
