# |-------------------------------------|
# | 4  |   |  2 | ------- |    |   |    |
# |____|   |____|         |____|   |____|
# |                                |    |
# |                                | 6  |
# |------                          -----|
# | 3                              |    |
# |____     ____           ____    |____|
# |    |   |    |         |    |   |    |
# |    |   |    | ------- |  1 |   |  5 |    
# |-------------------------------------|

- xyz: [path, 1.875, 0.225, 1.0]
- xyz: [path, 1.125, 1.775, 1.0]
- xyz: [path, 0.225, 0.725, 1.0]
- xyz: [path, 0.225, 1.775, 1.0]
- xyz: [path, 2.775, 0.225, 1.0]
- xyz: [path, 2.775, 1.275, 1.0]