# # route1
- xyz: [path, 2.7, 0.55, 1.0]
- xyz: [path, 1.85, 0.4, 2.0]
# - xyz: [path, 1.85, 0.7, 2.0]
# - xyz: [path, 2.45, 0.25, 1.0]
# - xyz: [path, 0.2, 0.75, 1.0]
# - xyz: [path, 2.8, 1.75, 1.0]
# - xyz: [path, 0.6, 0.225, 1.0]
# - xyz: [path, 1.5, 1.8, 1]
# - xyz: [path, 1.5, 0.25, 1]
# - xyz: [path, 0.6, 0.225, 1]
# - xyz: [path, 1.5, 1.8, 1]

# # route2
# - xyz: [path, 2, 0.5, 1]
# - xyz: [path, 2, 0.5, 1]
# - xyz: [path, 1, 0.5, 0.75]
# - xyz: [path, 2, 0.5, 1]
# - xyz: [path, 1, 0.5, 1]
# - xyz: [path, 2, 0.5, 1]

# # route3
# - xyz: [path, 2.7, 0.7, 1]
# - xyz: [path, 2.7, 0.7, 1]
# - xyz: [path, 2.7, 1.3, 1]
# - xyz: [path, 2.7, 0.7, 0.75]
# - xyz: [path, 2.7, 1.3, 1]
# - xyz: [path, 2.7, 0.7, 1]
# - xyz: [path, 2.7, 1.3, 1]
# - xyz: [path, 2.7, 0.7, 1]
# - xyz: [path, 2.7, 1.3, 1]
# - xyz: [path, 2.7, 0.7, 1]

# # route4
# - xyz: [path, 0.2, 0.2, 1]
# - xyz: [path, 0.2, 0.2, 1]
# - xyz: [path, 0.2, 1.8, 1]
# - xyz: [path, 0.2, 0.2, 0.75]
# - xyz: [path, 0.2, 1.8, 1]
# - xyz: [path, 0.2, 0.2, 1]
# - xyz: [path, 0.2, 1.8, 1]
# - xyz: [path, 0.2, 0.2, 1]
# - xyz: [path, 0.2, 1.8, 1]
# - xyz: [path, 0.2, 0.2, 0.75]
# - xyz: [path, 0.2, 1.8, 1]
# - xyz: [path, 0.2, 0.2, 1]
# - xyz: [path, 0.2, 1.8, 1]

# #  route5 #goals is too near!!!!
# - xyz: [path, 0.2, 0.345, 1]
# - xyz: [path, 0.2, 0.345, 1]
# - xyz: [path, 0.2, 0.345, 1]
# - xyz: [path, 0.2, 0.345, 1]
# - xyz: [path, 2.8, 0.345, 1]

# # route6
# - xyz: [path, 0.2, 0.5, 1]
# - xyz: [path, 0.2, 0.5, 1]
# - xyz: [path, 2.8, 0.5, 1]
# - xyz: [path, 0.2, 0.5, 1]
# - xyz: [path, 2.8, 0.5, 1]
# - xyz: [path, 0.2, 0.5, 1]
# - xyz: [path, 2.8, 0.5, 1]

# # route all
# - xyz: [path, 2.7, 0.7, 1]
# - xyz: [path, 2.7, 0.7, 1]
# - xyz: [path, 2.7, 1.3, 1]
# - xyz: [path, 2.7, 0.7, 0.75]
# - xyz: [path, 2.7, 1.3, 1]
# - xyz: [path, 2.7, 0.7, 1]
# - xyz: [path, 2.7, 1.3, 1]
# - xyz: [path, 2.7, 0.7, 1]
# - xyz: [path, 2.7, 1.3, 1]
# - xyz: [path, 2.7, 0.7, 1]
# - xyz: [path, 2.7, 1.3, 1]
# - xyz: [path, 2.7, 0.7, 1]
# - xyz: [path, 2.7, 1.3, 1]
# - xyz: [path, 2.7, 0.7, 1]
# - xyz: [path, 2.7, 1.3, 1]
- 
# - xyz: [path, 2, 0.5, 1]
# - xyz: [path, 2, 0.5, 1]
# - xyz: [path, 1, 0.5, 0.75]
# - xyz: [path, 2, 0.5, 1]
# - xyz: [path, 1, 0.5, 1]
# - xyz: [path, 2, 0.5, 1]