# |-------------------------------------|
# |    |   |    | ------- |    |   |    |
# |____|4 3|_18_|         |____|   |__7_|
# |          2                          |
# |  5                                  |
# |------                          -----|
# |                                     |
# |____     ____           ____     ____|
# |  6 |   |    |         |    |   |    |
# |    |   |    | ------- |    |   |    |
# |-------------------------------------|

- xyz: [path, 1.125, 1.775, 1.0]
- xyz: [path, 1.125, 1.275, 1.0]
- xyz: [path, 0.775, 1.775, 1.0]
- xyz: [path, 0.575, 1.775, 1.0]
- xyz: [path, 0.225, 1.275, 1.0]
- xyz: [path, 0.225, 0.225, 1.0]
- xyz: [path, 2.775, 1.775, 1.0]
- xyz: [path, 1.125, 1.775, 1.0]