# |-------------------------------------|
# |    |   |    | ------- |    |   |    |
# |____|   |____|         |____|   |____|
# |                                     |
# |                                     |
# |------                          -----|
# |                                     |
# |____     ____           ____     ____|
# |    |   |    |         |    |   |    |
# |    |   |    | ------- |    |   |    |    
# |-------------------------------------|

- xyz: [1.125, 0.225, 1.0]
- xyz: [1.125, 0.725, 1.0]
- xyz: [0.775, 0.225, 1.0]
- xyz: [0.575, 0.225, 1.0]
- xyz: [0.225, 0.725, 1.0]
- xyz: [0.225, 1.775, 1.0]
- xyz: [2.775, 0.225, 1.0]
- xyz: [1.125, 0.225, 1.0]