obstacle_range: 3
raytrace_range: 3
footprint: [[0,0.15],[0.1299,0.075],[0.1299,-0.075],[0,-0.15],[-0.1299,-0.075],[-0.1299,0.075]]
map_topic: map
subscribe_to_updates: true
global_frame: map
robot_base_frame: base_link
update_frequency: 10.0
publish_frequency: 10.0


plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"} 
# ... my own plugins   
  # - {name: simple_layer, type: "simple_layer_namespace::GridLayer"}   
  # - {name: simple_layer, type: "simple_layer_namespace::SimpleLayer"}  
  - {name: lidar_obstacle_layer, type: "lidar_obstacle_layer_namespace::LidarObstacleLayer"} 
# ... final layer
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
   

static_layer:
  enabled: true
  map_topic: map
  subscribe_to_updates: false

lidar_obstacle_layer:
  enabled: true
  obstacle_topic: test
  obstacle_radius: 0.15
  expand_division: 30 #total points of expanded profile

simple_layer:
  enabled: true

inflation_layer:
  enabled: true
  cost_scaling_factor: 3.0
  inflation_radius: 0.2

