global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  static_map: true
  rolling_window: false

  update_frequency: 10
  publish_frequency: 2.0
  transform_tolerance: 0.2
  resolution: 0.1
  visualize_potential: true

