local_costmap:
  update_frequency: 1  # 10
  # publish_frequency: 10.0
  # transform_tolerance: 0.2
  # static_map: false
  # rolling_window: true
  # resolution: 0.01
  # inflation_radius: 0.15
  # width: 1.0
  # height: 1.0

  plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}


