prohibition_areas:
 # your first prohibited area is only a point
 - [0.5,0.5]
 # now we define a line
 # it will become the thickness of the costmap resolution
 - [[1, 1],
    [2, 1]]
 # and last but not least a polygon with an individual number of points
#  - [[-11.15, -15.614],
#     [-12.35, -13.89],
#     [-10.05, -12.218]]